services:
  redis:
    container_name: springboot_simple_template_redis
    image: redis:latest
    ports:
      - "6380:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 2s
      timeout: 3s
      retries: 60
    networks:
      - springboot-simple-template
  mysql:
    container_name: springboot_simple_template_mysql
    image: mysql:8
    ports:
      - '3300:3306'
    environment:
      TZ: 'Asia/Seoul'
      MYSQL_DATABASE: springboot_simple_template
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./infra/mysql/data:/var/lib/mysql
    networks:
      - springboot-simple-template
networks:
  springboot-simple-template:
    name: springboot-simple-template
    driver: bridge
