spring.config.activate.on-profile: default, local

server:
  servlet:
    context-path: /api

spring:
  config:
    import:
      - core.yaml
      - redis.yaml

springdoc:
  swagger-ui:
    path: /docs

---
spring.config.activate.on-profile: dev