FROM openjdk:17-jdk-slim-buster as Builder

ARG WORK_DIR=/usr/bin/app

# workdir
WORKDIR ${WORK_DIR}

#
ARG JAR_FILE=build/libs/\*.jar

#
COPY ${JAR_FILE} app.jar

#
RUN ["java", "-Djarmode=layertools", "-jar", "app.jar", "extract"]

# runner
FROM openjdk:17-jdk-slim-buster AS runner

#
ARG WORK_DIR=/usr/bin/app

#
WORKDIR ${WORK_DIR}

#
COPY --from=builder ${WORK_DIR}/dependencies/ ./
COPY --from=builder ${WORK_DIR}/spring-boot-loader/ ./
COPY --from=builder ${WORK_DIR}/snapshot-dependencies/ ./
COPY --from=builder ${WORK_DIR}/application/ ./


# TODO. 확인 필요
ENTRYPOINT [ "java", "-Dspring.profiles.active=dev", "org.springframework.boot.loader.JarLauncher" ]